### ISSUE TITLE
Database selection and discussion

### ISSUE THREAD

**Issue by prsnt** [professor-greebie/SENG8080-1-field_project#102]
We should go with the **MongoDB**. I had a word with Data Collection, Data research and Devops team for the same.

**Comment by prathmeshjani** [comment]
LDTM!

**Comment by sumukhdhawade** [comment]
LGTM but make sure to plan and optimize your data schema to ensure efficient querying and scalability.

**Comment by Lakshay1505** [comment]
review this please devops team @kthamman @whosyus @ChandanSulimaltheSannappa

**Comment by prsnt** [comment]
> review this please devops team @kthamman @whosyus @ChandanSulimaltheSannappa

Yes, please review and add your inputs here.
Thanks @Lakshay1505

**Comment by kthamman** [comment]
Checking for mongodb database.

**Comment by prsnt** [comment]
> Checking for mongodb database.

Hi @kthamman If you are done with checking then Please approve and close this issue.
Thank you.

**Comment by kthamman** [comment]
Looks good!
