### ISSUE TITLE
Issue in downloading s3 data set - Data collection team

### ISSUE THREAD

**Issue by garima6876** [professor-greebie/SENG8080-1-field_project#106]
After installing AWS CLI and running command .\Data_Collection_From_AWS_S3.ps1, genome browser folder has been made but how to perform further steps ? its not visible as mentioned .

**Comment by SindhuParkaviS** [comment]
@garima6876  The steps to run the Powershell file are in the readme.md file. Also please use the Python script([data_collection_from_s3.py](https://github.com/professor-greebie/SENG8080-1-field_project/blob/main/src/data_collection_from_s3.py)), since it will do the recursive unzipping.
