### ISSUE TITLE
Unable to access the actual data.

### ISSUE THREAD

**Issue by prathmeshjani** [professor-greebie/SENG8080-1-field_project#108]
After following the steps mentioned, we still cannot receive the actual data on which we should do the data quality steps. 

![Screenshot 2023-07-27 141814](https://github.com/professor-greebie/SENG8080-1-field_project/assets/69078331/3de350e9-1f9b-477b-9dd0-4b5f7820e3fd)

As you can see, we have unzipped the files but can still not get the file we should be working on.

**Comment by prsnt** [comment]
> After following the steps mentioned, we still cannot receive the actual data on which we should do the data quality steps.
> 
> ![Screenshot 2023-07-27 141814](https://user-images.githubusercontent.com/69078331/256628916-3de350e9-1f9b-477b-9dd0-4b5f7820e3fd.png)
> 
> As you can see, we have unzipped the files but can still not get the file we should be working on.

@prathmeshjani I have also tried the same. I got the same files. I am not sure how to work on these files. Please tag here who provided the data.
