### ISSUE TITLE
Looking for data file 

### ISSUE THREAD

**Issue by prathmeshjani** [professor-greebie/SENG8080-1-field_project#109]
The data quality group is looking for the actual data file for processing the data quality check. If your team has any suggestions on how to access the data file which has the format of .csv or an Excel file then please reach out to us.

**Comment by Lakshay1505** [comment]
Soon will try to deliver as all things are working fine but still data is not accessible as we are not be able to fetch. If you do have data file like csv or excel please do provide @SindhuParkaviS @JJaramillomejia0773 @B055man4

**Comment by SindhuParkaviS** [comment]
@Lakshay1505 @prathmeshjani  I think we do not have any data files. In the code for data collection, we can change the s3 source to retrieve the data files. Also, please check with the data storage team, if they have retrieved the data files and stored them in the database.

**Comment by JJaramillomejia0773** [comment]
Hello @Lakshay1505 @prathmeshjani the data is not physical; we designed the way to obtain it, maybe the storage team might already download it

**Comment by Lakshay1505** [comment]
I got your point. Everything is running fine, but at the final step, we won't be able to retrieve the data looking for the Data Storage team to respond. @prsnt  @professor-greebie  Looking forward, professor, for your valuable revert and collection team has just one member.

**Comment by prsnt** [comment]
Hi @Lakshay1505 @JJaramillomejia0773 

Yes, Data is downloaded as per the instruction given in the README.

The S3 bucket is also ready to store the data. The data is not being held in S3 and which format is this ?
I need help from the data collection on how to use this data as I have completed all the steps but did not reach to the data yet.

**Comment by JJaramillomejia0773** [comment]
Hi @prsnt , i dont know what type of data is , may be @SindhuParkaviS  Khonws?

**Comment by HareeshCon** [comment]
If we can transform the data and load in an excel or CSV format(easily readable to asses), it would be easier for the Data Visualization team to perform a visualization. The current **fa format** is not legible to make an insight.

**Comment by HareeshCon** [comment]
> Hi @Lakshay1505 @JJaramillomejia0773
> 
> Yes, Data is downloaded as per the instruction given in the README.
> 
> The S3 bucket is also ready to store the data. The data is not being held in S3 and which format is this ? I need help from the data collection on how to use this data as I have completed all the steps but did not reach to the data yet.

@prsnt , thanks for the creation of S3 bucket.

**Comment by SindhuParkaviS** [comment]
@prsnt @HareeshCon  I think you need to change the s3_folder_key of the S3 bucket as per data research to retrieve the actual data. @Lakshay1505  Could you please suggest to them which S3 source they need to use? Also from my understanding, the file format will be tab-delimited with a ".txt" extension. Please confirm with Professor for this.

**Comment by Zarnagohil** [comment]
We can use  this link to understand gtf file https://en.wikipedia.org/wiki/General_feature_format @prathmeshjani @Nisha8898 @garima6876 @vishalbarvaliya @darshan8055 @karansorathiya @patelkaran002007 @MrunalWavdhane2303

**Comment by gahlawat36** [comment]
Hey, I am in the Data Visualization team, and I went through the discussion but couldn't find any link or information on where I can download the data. I ran the data_collection_from_s3.py script, and it resulted in a bunch of compressed files. Could someone help me in getting the data so that we can start analyzing it?

**Comment by vishalbarvaliya** [comment]
Hey @gahlawat36, For now, we are cleaning the files that we extracted from compressed files.

**Comment by Lakshay1505** [comment]
As per the discussion with @dataquality @vishalbarvaliya we are cleaning up the data and merging it. soon will come with the data file as there are lot of encrypted files. Thanks everyone If needed anything just come with the question happy to assist and work.

**Comment by gahlawat36** [comment]
The Data files are available in the Data Quality folder.
