### ISSUE TITLE
Need Metadata File, Urgent

### ISSUE THREAD

**Issue by gahlawat36** [professor-greebie/SENG8080-1-field_project#114]
Hello team, I downloaded the data and to do further analysis and visualization I need a Data dictionary file or Metadata if available.

**Comment by prathmeshjani** [comment]
Hey! Thanks for reaching out. As already mentioned under the steps performed, you look for GFF (Genome Feature Format) on Wikipedia to get a better understanding of the data. 
https://en.wikipedia.org/wiki/General_feature_format

**Comment by gahlawat36** [comment]
Great, thanks.
