### ISSUE TITLE
Decide on Data to Collect

### ISSUE THREAD

**Issue by professor-greebie** [professor-greebie/SENG8080-1-field_project#15]
The Data Collection team will need to know what data to collect and how it is formatted.

**Comment by Lakshay1505** [comment]
kangaroo rat
https://hgdownload.soe.ucsc.edu/goldenPath/dipOrd1/bigZips/genes/

rat
https://hgdownload.soe.ucsc.edu/goldenPath/rn7/bigZips/genes/

Either way, we can go for the findings of Rat and Kangaroo Rat to find out the behaviour and how to react to things in some alarming or challenging situations.

**Comment by prsnt** [comment]
lgtm
