### ISSUE TITLE
Solution for Cross-platform use of the service

### ISSUE THREAD

**Issue by professor-greebie** [professor-greebie/SENG8080-1-field_project#87]
The scripts provided for data collection are currently in Powershell which are not supported by Linux or Mac. We will need a solution to manage cross-platform usage.

**Comment by Lakshay1505** [comment]
Well, we can look out for other options, such as Python.

**Comment by SindhuParkaviS** [comment]
Thanks, @Lakshay1505  We have already started implementing the Python code for data collection from s3 and are awaiting the professor's review. I will let you know once the code has been reviewed and merged into the main repository.

**Comment by Mukeshyarlagadda** [comment]
issue resolved.

**Comment by JJaramillomejia0773** [comment]
@Lakshay1505 the python code is done, you can review it

**Comment by Lakshay1505** [comment]
Hey, team, kindly review and update @Jeevan1992 @mansi0404 @sumukhdhawade

**Comment by sumukhdhawade** [comment]
LGTM @Lakshay1505

**Comment by Jeevan1992** [comment]
lgtm @Lakshay1505

**Comment by amandeep-amandeep** [comment]
lgtm 👍🏽 @Lakshay1505

**Comment by SindhuParkaviS** [comment]
Thank you, Guys. Closing this request

**Comment by mansi0404** [comment]
Python code running fine.@Lakshay1505

**Comment by Lakshay1505** [comment]
Thanks a lot for the review guys @Jeevan1992 @mansi0404 @amandeep-amandeep @sumukhdhawade
