### ISSUE TITLE
Creating a JuPyter skeleton for Visualization

### ISSUE THREAD

**Issue by HareeshCon** [professor-greebie/SENG8080-1-field_project#99]
For visualizing the data at the end of the project, we are preparing a JuPyter notebook and making a skeleton.
The file is subjected to further enhancements in the future once the data is prepared and processed.

**Comment by JJaramillomejia0773** [comment]
@HareeshCon LGTM

**Comment by Lakshay1505** [comment]
Platform Deployed @professor-greebie @HareeshCon
